#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/site-confs \
	/run/apache2 \
	/var/cache/smokeping

# copy config files

PREV_DIR=$(pwd)

	cd /defaults/smoke-conf || exit
	shopt -s globstar nullglob
	for i in *
 	do
	[[ ! -e "/config/${i}" ]] && cp -v "${i}" "/config/${i}"
	done

cd "${PREV_DIR}" || exit

# make symlinks
[[ ! -L /var/www/localhost/smokeping ]] && \
	ln -sf /usr/share/webapps/smokeping /var/www/localhost/smokeping

[[ ! -L /var/www/localhost/smokeping/cache ]] && \
	ln -sf	/var/cache/smokeping /var/www/localhost/smokeping/cache

[[ ! -e /etc/ssmtp/ssmtp.conf ]] && \
	cp /config/ssmtp.conf /etc/ssmtp/ssmtp.conf

# permissions
chown -R abc:abc \
	/config \
	/data \
	/usr/share/webapps/smokeping \
	/var/cache/smokeping \
	/var/www/localhost/smokeping
